# Generated by Django 6.0.5 on 2026-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_alter_observation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="assessment_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="current_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_rego_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="rule_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="vex_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation_log",
            name="vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
