# Generated by Django 6.0.6 on 2026-07-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_remove_product_notification_ms_teams_webhook_v2_format'),
        ('core', '0093_observation_log_general_rule_rego_and_more'),
    ]

    operations = [
    ]
