# Generated by Django 6.0.5 on 2026-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0019_alter_rule_new_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="new_vex_remediations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
