# Generated by Django 6.0.6 on 2026-07-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0020_rule_new_vex_remediations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rule",
            old_name="approval_remark",
            new_name="rejection_remark",
        ),
    ]
