# Generated by Django 6.0.6 on 2026-07-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_observation_log_general_rule_rego_and_more"),
        ("notifications", "0002_observation_title_notified_alter_notification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Assessment request", "Assessment request"),
                    ("Assessment result", "Assessment result"),
                    ("Exception", "Exception"),
                    ("Observation", "Observation"),
                    ("Observation title", "Observation title"),
                    ("Security gate", "Security gate"),
                    ("Task", "Task"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="observation_log",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.observation_log",
            ),
        ),
        migrations.CreateModel(
            name="Notification_Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_recipients",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "commons_notification_recipient",
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("type", "observation_log"),
                name="unique_notification_type_observation_log",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification_recipient",
            constraint=models.UniqueConstraint(
                fields=("notification", "user"),
                name="unique_notification_recipient",
            ),
        ),
    ]
