# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_observation_title_notified_alter_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Exception", "Exception"),
                    ("Observation", "Observation"),
                    ("Observation title", "Observation title"),
                    ("Delete request", "Delete request"),
                    ("Security gate", "Security gate"),
                    ("Task", "Task"),
                ],
                max_length=20,
            ),
        ),
    ]
